"""empty message

Revision ID: 99ffc045c3ca
Revises: c0292b12af4b
Create Date: 2022-04-14 13:13:37.285620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99ffc045c3ca'
down_revision = 'c0292b12af4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie_list', 'new')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie_list', sa.Column('new', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
